# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95fdfb9c5c00c2933b80ac80cf08c65a41551f7b56556fd0bcf551f8249876ff5dd293a744b8ce8fad30d4c410f284b1d783b5cdb5bc1814177a889edca2f074

test:
  secret_key_base: 4d08c36ec37f6500d8f0df3c09a4de95a80144b2f77f0e53998ad033c298e1fc8bd4273194c39a082b5d5cfb642f47dfef46e3edffb08deeba7900ad83566324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
